name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install mkdocs
          pip3 install mkdocs-minify-plugin
          pip3 install mkdocs-material
          pip3 install mkdocs-git-revision-date-plugin

      - name: Run custom Python script
        run: python3 MKDocs/update_general_pages.py

      - name: Deploy MkDocs Site
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: mkdocs gh-deploy --force
        working-directory: MKDocs