name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install mkdocs
    - run: pip install mkdocs-material
    - run: pwd
    - run: ls -l
    - run: python MKDocs/update_general_pages.py 
    - run: mkdocs gh-deploy --force
