name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip3 install mkdocs
    - run: pip3 install mkdocs-minify-plugin 
    - run: pip3 install mkdocs-material
    - run: python3 MKDocs/update_general_pages.py 
    - name: Deploy MkDocs Site
      run: mkdocs gh-deploy --force
      working-directory: MKDocs