# Project information
site_name: TIL
site_url: https://makenna-avakian.github.io/TIL/
site_author: Makenna Avakian
site_description: >-
  A place to store all the things I learn in a day.
# Repository
repo_name: makenna-avakian/TIL
repo_url: https://github.com/makenna-avakian/TIL


site_name: TIL
theme:
    name: material
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
    - search
    - minify:
        minify_html: true
    - git-revision-date
nav:
    - Home: index.md
    - Accessibility: Accessibility/general.md
    - Angular: Angular/general.md
    - CSS: CSS/general.md
    - Design-Patterns: Design-Patterns/general.md
    - Git: Git/general.md
    - HTML: HTML/general.md
    - jQuery: jQuery/general.md
    - React: React/general.md
    - Tailwind: Tailwind/general.md
    - Vite: Vite/general.md
extra_css:
    - assets/custom.css
extra_javascript:
    - assets/custom.js